import Link from "next/link";
import localFont from "@next/font/local";
import Head from "next/head";
import { useRouter } from "next/router";
import classNames from "classnames";

interface Props {
  children?: React.ReactNode;
}

export const pokeFont = localFont({ src: "../fonts/Pokemon.ttf" });


export default function Layout({ children }: Props) {
  const { pathname } = useRouter();

  return (
    <>
      <Head>
        <title>PokeQuiz!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={classNames("flex flex-col min-h-screen", pokeFont.className)} >
        <nav>
          <ul className="flex justify-center mt-4">
            <li>
              <Link
                href="/"
                className={classNames(
                  "p-2 mx-2 hover:translate-y-px",
                  { "border-b-2 border-black": pathname === "/" }
                )}
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                href="/high-scores"
                className={classNames(
                  "p-2 mx-2 hover:translate-y-px",
                  { "border-b-2 border-black": pathname === "/high-scores" }
                )}
              >
                High Scores
              </Link>
            </li>
          </ul>
        </nav>

        <main className="flex-grow flex justify-center">
          {children}
        </main>
      </div>
    </>
  )
}
